apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  steps:
    - name: lint
      image: node:18
      script: |
        npm install
        npm run lint
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: jest
      image: node:18
      script: |
        npm install
        npm test
``
